export const projects = [
    {
        title: "Hometown Homepage",
        img: "./images/projects/hometown.png",
        desc: "A single page website describing your hometown and what you can do there.",
        instructions: "<ul><li>Lorem ipsum dolor sit amet,</li><li>consectetur adipiscing elit. Mauris finibus</li><li>ac ligula id aliquet. Etiam ultrices mi tellus, sit amet consectetur</li></ul> justo eleifend ut. Vestibulum ullamcorper hendrerit felis id auctor. In lacus orci, vestibulum nec laoreet a, rutrum ac sapien. Etiam consectetur risus sed erat dignissim, quis facilisis ligula venenatis. Ut ut lorem a nisl efficitur iaculis. Ut placerat felis at mauris elementum imperdiet. Pellentesque ornare massa et ante fringilla tristique. Vivamus a interdum elit. In ultricies, mi in venenatis malesuada, neque odio venenatis nunc, et blandit ex ex sit amet neque. Suspendisse potenti. Phasellus quis dictum ante. Etiam vehicula convallis luctus. In vestibulum, mauris efficitur commodo vehicula, tortor dolor iaculis nibh, vel vehicula libero ipsum vel neque. Pellentesque lobortis, mi nec dictum feugiat, orci mauris gravida magna, in pharetra neque ante nec sem. Aenean ut leo ultricies, fermentum risus at, condimentum lacus. Sed risus eros, commodo quis blandit eget, facilisis ac libero. Morbi vulputate lacus quam, vestibulum vulputate metus molestie eget. Nunc non mollis urna. Sed ac viverra lorem. Ut laoreet pulvinar orci, id cursus lorem porta eu. Duis eleifend dolor nec lectus semper ultricies. Nam vulputate erat ac pellentesque pellentesque. Duis enim urna, fringilla nec cursus at, faucibus nec magna.",
        github: "https://github.com/Raehale/home-town",
        url: "https://aquamarine-empanada-f3f2ed.netlify.app/",
        languages: ["html", "css"],
        id: 0,
    },
    {
        title: "Inspirational Quote Page",
        img: "./images/projects/hometown.png",
        desc: "A single page website that displays a quote.",
        instructions: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris finibus ac ligula id aliquet. Etiam ultrices mi tellus, sit amet consectetur justo eleifend ut. Vestibulum ullamcorper hendrerit felis id auctor. In lacus orci, vestibulum nec laoreet a, rutrum ac sapien. Etiam consectetur risus sed erat dignissim, quis facilisis ligula venenatis. Ut ut lorem a nisl efficitur iaculis. Ut placerat felis at mauris elementum imperdiet. Pellentesque ornare massa et ante fringilla tristique. Vivamus a interdum elit. In ultricies, mi in venenatis malesuada, neque odio venenatis nunc, et blandit ex ex sit amet neque. Suspendisse potenti. Phasellus quis dictum ante. Etiam vehicula convallis luctus. In vestibulum, mauris efficitur commodo vehicula, tortor dolor iaculis nibh, vel vehicula libero ipsum vel neque. Pellentesque lobortis, mi nec dictum feugiat, orci mauris gravida magna, in pharetra neque ante nec sem. Aenean ut leo ultricies, fermentum risus at, condimentum lacus. Sed risus eros, commodo quis blandit eget, facilisis ac libero. Morbi vulputate lacus quam, vestibulum vulputate metus molestie eget. Nunc non mollis urna. Sed ac viverra lorem. Ut laoreet pulvinar orci, id cursus lorem porta eu. Duis eleifend dolor nec lectus semper ultricies. Nam vulputate erat ac pellentesque pellentesque. Duis enim urna, fringilla nec cursus at, faucibus nec magna.",
        github: "https://github.com/Raehale/home-town",
        url: "https://aquamarine-empanada-f3f2ed.netlify.app/",
        languages: ["html", "css"],
        id: 1,
    },
    {
        title: "Basketball Scoreboard",
        img: "./images/projects/hometown.png",
        desc: "A simple scoreboard that keeps score between two teams with scores of one, two, or three.",
        instructions: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris finibus ac ligula id aliquet. Etiam ultrices mi tellus, sit amet consectetur justo eleifend ut. Vestibulum ullamcorper hendrerit felis id auctor. In lacus orci, vestibulum nec laoreet a, rutrum ac sapien. Etiam consectetur risus sed erat dignissim, quis facilisis ligula venenatis. Ut ut lorem a nisl efficitur iaculis. Ut placerat felis at mauris elementum imperdiet. Pellentesque ornare massa et ante fringilla tristique. Vivamus a interdum elit. In ultricies, mi in venenatis malesuada, neque odio venenatis nunc, et blandit ex ex sit amet neque. Suspendisse potenti. Phasellus quis dictum ante. Etiam vehicula convallis luctus. In vestibulum, mauris efficitur commodo vehicula, tortor dolor iaculis nibh, vel vehicula libero ipsum vel neque. Pellentesque lobortis, mi nec dictum feugiat, orci mauris gravida magna, in pharetra neque ante nec sem. Aenean ut leo ultricies, fermentum risus at, condimentum lacus. Sed risus eros, commodo quis blandit eget, facilisis ac libero. Morbi vulputate lacus quam, vestibulum vulputate metus molestie eget. Nunc non mollis urna. Sed ac viverra lorem. Ut laoreet pulvinar orci, id cursus lorem porta eu. Duis eleifend dolor nec lectus semper ultricies. Nam vulputate erat ac pellentesque pellentesque. Duis enim urna, fringilla nec cursus at, faucibus nec magna.",
        github: "https://github.com/Raehale/home-town",
        url: "https://aquamarine-empanada-f3f2ed.netlify.app/",
        languages: ["html", "css", "JavaScript"],
        id: 2,
    },
    {
        title: "Password Generator",
        img: "./images/projects/hometown.png",
        desc: "A password generator that generates a random password for the user.",
        instructions: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris finibus ac ligula id aliquet. Etiam ultrices mi tellus, sit amet consectetur justo eleifend ut. Vestibulum ullamcorper hendrerit felis id auctor. In lacus orci, vestibulum nec laoreet a, rutrum ac sapien. Etiam consectetur risus sed erat dignissim, quis facilisis ligula venenatis. Ut ut lorem a nisl efficitur iaculis. Ut placerat felis at mauris elementum imperdiet. Pellentesque ornare massa et ante fringilla tristique. Vivamus a interdum elit. In ultricies, mi in venenatis malesuada, neque odio venenatis nunc, et blandit ex ex sit amet neque. Suspendisse potenti. Phasellus quis dictum ante. Etiam vehicula convallis luctus. In vestibulum, mauris efficitur commodo vehicula, tortor dolor iaculis nibh, vel vehicula libero ipsum vel neque. Pellentesque lobortis, mi nec dictum feugiat, orci mauris gravida magna, in pharetra neque ante nec sem. Aenean ut leo ultricies, fermentum risus at, condimentum lacus. Sed risus eros, commodo quis blandit eget, facilisis ac libero. Morbi vulputate lacus quam, vestibulum vulputate metus molestie eget. Nunc non mollis urna. Sed ac viverra lorem. Ut laoreet pulvinar orci, id cursus lorem porta eu. Duis eleifend dolor nec lectus semper ultricies. Nam vulputate erat ac pellentesque pellentesque. Duis enim urna, fringilla nec cursus at, faucibus nec magna.",
        github: "https://github.com/Raehale/home-town",
        url: "https://aquamarine-empanada-f3f2ed.netlify.app/",
        languages: ["html", "css", "JavaScript"],
        id: 3,
    },
    // {
    //     title: "",
    //     img: "",
    //     desc: "",
    //     instructions: "",
    //     github: "",
    //     url: "",
    //     languages: ["html", "css", "JavaScript", "API", "React", "Firebase"],
    //     id: ,
    // },
]